# Useful Functions

In [ ]:
import csv
from kan import *
from kan.utils import ex_round
from bayes_opt import BayesianOptimization
from sklearn.model_selection import StratifiedKFold

torch.set_default_dtype(torch.float64)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset, Subset
import seaborn as sns
import copy

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)



cuda


In [ ]:
def load_dataset(csv_file_path_list, device='cpu'):

    inputs = []
    labels = []

    for csv_file_path in csv_file_path_list:
        with open(csv_file_path, 'r', newline='', encoding='utf-8') as csvfile:
            reader = csv.reader(csvfile)
            for row in reader:
                n = len(row)-1
                input_row = list(map(float, row[0:n]))
                label = int(row[n])
                inputs.append(input_row)
                labels.append(label)

    dataset = {
        'input': torch.tensor(inputs, dtype=torch.double).to(device),
        'label': torch.tensor(labels, dtype=torch.double).to(device)
    }
    # if type is not float silu (in model.fit()) will not run: "silu_cuda" not implemented for 'double'

    return dataset

def standardize_dataset(dataset, mean=None, std=None):
    '''
    dataset is a dictionary with keys 'input' and 'label':
        dataset = {
            'input': dataset['input'],
            'label': dataset['label']
        }
    mean and std are the statistics with which we standardize the dataset.

    If mean and std are not provided, they will be calculated from the dataset are returned by the function.
    '''

    if mean is None:
        mean = dataset['input'].mean(dim=0)
    if std is None:
        std = dataset['input'].std(dim=0)
    standardized = (dataset['input'] - mean) / std
    dataset['input'] = standardized

    return dataset, mean, std

def standardize_dataset_raw(dataset, mean=None, std=None, channels=4, timesteps=20):
    # Standardizes dataset with format (N, channels*timesteps), flattened as [ch1_t1, ch2_t1, ch3_t1, ch4_t1, ..., ch1_t20, ..., ch4_t20]
    X = dataset['input']  
    
    N = X.shape[0]
    X_reshaped = X.view(N, timesteps, channels)  # (N, timesteps, channels)

    if mean is None:
        mean = X_reshaped.mean(dim=(0, 1))
    if std is None:
        std = X_reshaped.std(dim=(0, 1))
    standardized = (X_reshaped - mean) / std

    dataset['input'] = standardized.view(N, timesteps * channels)  # back to original flat layout

    return dataset, mean, std

def get_class_weights(dataset):

    # Flatten the labels to 1D for proper bincount 
    train_labels_flattened = dataset['label'].int().view(-1).cpu().numpy()

    # Calculate class weights based on the class distribution
    class_counts = np.bincount(train_labels_flattened)
    num_total = train_labels_flattened.size
    class_weights = num_total / (5 * class_counts)  # Inverse frequency of each class
    class_weights = torch.tensor(class_weights, dtype=torch.float32).to(device)
    
    return class_weights

def train_model(model, train_loader, opt, loss_fn, steps, lamb=0, early_stopping=False, datatype=torch.float, singularity_avoiding=False):
    '''
    early_stopping (boolean): If True, the model with the lowest training loss is saved. If False, return the model of the final epoch.
    early_stopping (int): Patience for early stopping.
    '''

    if early_stopping:
        best_loss = float('inf')
        best_model_state = copy.deepcopy(model.state_dict())
    if isinstance(early_stopping, int):
        patience = early_stopping
        no_improvement_count = 0

    accuracy_history = []
    loss_history = []
    for i in range(steps):
        train_batch_num = 0
        running_train_accuracy = 0
        running_train_loss = 0

        for batch_inputs, batch_labels in train_loader:
            model.train()

            inputs = batch_inputs.to(dtype=datatype).to(device)
            labels = batch_labels.to(device)

            global loss, outputs
            
            # Most optimizers just use optimizer.step(), but certains optimizers require optimizer.step(closure) (e.g., LBFGS). It is used when the optimizer evaluates model and gradient multiple times per step.
            def closure():
                global loss, outputs
                opt.zero_grad()
                outputs = model(inputs, singularity_avoiding=singularity_avoiding)
                # print(outputs.float(), labels.long())
                loss = loss_fn(outputs.to(dtype=datatype), labels.long())
                reg = model.get_reg(reg_metric='edge_forward_spline_n', lamb_l1=1., lamb_entropy=1., lamb_coef=0., lamb_coefdiff=0.)
                loss = loss + lamb*reg
                loss.backward()
                return loss
            
            opt.step(closure)
            
            with torch.no_grad():
                preds = torch.argmax(outputs, dim=1)
                batch_accuracy = (torch.sum(preds == labels) / torch.numel(labels)).item()
                running_train_accuracy += batch_accuracy
                batch_loss = loss.item()
                running_train_loss += batch_loss
                train_batch_num += 1

        train_accuracy = running_train_accuracy / train_batch_num
        train_loss = running_train_loss / train_batch_num

        if i % 1 == 0:
            print(f"Epoch: {i}, Train Acc: {train_accuracy}, Loss: {train_loss}")

        accuracy_history.append(train_accuracy)
        loss_history.append(train_loss)

        if early_stopping:
            if train_loss < best_loss:
                best_loss = train_loss
                best_model_state = copy.deepcopy(model.state_dict())    # Deep copy is needed here because model.state_dict() gives tensors that reference the model's parameters
            elif isinstance(early_stopping, int):
                no_improvement_count += 1

        if torch.isnan(loss).any():
            print(f"Epoch {i}: NaN loss detected, stopping this run.")
            break

        if isinstance(early_stopping, int) and no_improvement_count >= patience:
            break

    if early_stopping:
        if best_model_state is not None:
            model.load_state_dict(best_model_state)
        else:
            print("Warning: no valid checkpoint found (diverged on epoch 0)")

    model.eval()
    with torch.no_grad():
        _ = model(inputs)    # refresh safe activations for plotting. Note that model.load_state_dict(best_model_state) alone does not copy the activation mask, may still have nan
    
    return accuracy_history, loss_history



def compute_confusion_matrix(preds, labels, device=None):

    preds = torch.as_tensor(preds)
    labels = torch.as_tensor(labels)

    if device is None:
        device = preds.device

    num_classes = int(max(preds.max(), labels.max()).item() + 1)
    cm = torch.zeros(num_classes, num_classes, dtype=torch.int64, device=device)

    for t, p in zip(labels, preds):
        cm[t, p] += 1

    return cm


def plot_confusion_matrix(cm, class_names=None, normalize=False, title=""):

    if isinstance(cm, torch.Tensor):
        cm = cm.cpu().numpy()

    num_classes = cm.shape[0]
    if class_names is None:
        class_names = [str(i) for i in range(num_classes)]

    if normalize:
        cm_colour = cm.astype(np.float64)
        row_sums = cm_colour.sum(axis=1, keepdims=True)
        row_sums[row_sums == 0] = 1  # avoid division by zero
        cm_colour = cm_colour / row_sums
    else:
        cm_colour = cm

    fontsize = 13

    plt.figure(figsize=(6, 5))  
    sns.heatmap(
        data=cm_colour,
        annot=cm,
        fmt="d",
        cmap="Blues",
        cbar=False,
        xticklabels=class_names,
        yticklabels=class_names,
        annot_kws={"fontsize": fontsize}
    )
    plt.xlabel("Predicted Label", fontsize=fontsize)
    plt.ylabel("True Label", fontsize=fontsize)
    plt.title(title, fontsize=fontsize)
    plt.xticks(fontsize=fontsize, rotation=0)
    plt.yticks(fontsize=fontsize, rotation=0)
    plt.tick_params(axis='both', which='both', length=0)
    plt.tight_layout()
    plt.show()

def compute_metrics(cm):

    cm = cm.float()
    
    TP = cm.diag()
    precision = TP / (cm.sum(0) + 1e-8)  # sum over column = predicted positives
    recall = TP / (cm.sum(1) + 1e-8)     # sum over row = actual positives
    f1 = 2 * precision * recall / (precision + recall + 1e-8)
    
    metrics = {
        'precision_per_class': precision.tolist(),
        'recall_per_class': recall.tolist(),
        'f1_per_class': f1.tolist()
    }
    
    return metrics

def compute_binary_metrics(cm):
    '''
    Computes binary precision, recall, F1, and accuracy where negative class is class 0 and positive class is all remaining classes.
    '''

    cm = cm.float()

    # Binary confusion matrix
    TP = cm[1:, 1:].sum()
    FN = cm[1:, 0].sum()
    FP = cm[0, 1:].sum()
    TN = cm[0, 0]

    precision = TP / (TP + FP + 1e-8)
    recall = TP / (TP + FN + 1e-8)
    specificity = TN / (TN + FP + 1e-8)
    f1 = 2 * precision * recall / (precision + recall + 1e-8)
    accuracy = (TP + TN) / (cm.sum() + 1e-8)
    fn_rate = FN / (TP + FN + 1e-8)
    fp_rate = FP / (TN + FP + 1e-8)

    metrics = {
        "precision": precision.item(),
        "recall": recall.item(),
        "f1": f1.item(),
        "accuracy": accuracy.item(),
        "tp": TP.item(),
        "fp": FP.item(),
        "fn": FN.item(),
        "tn": TN.item(),
        "fn_rate": fn_rate.item(),
        "fp_rate": fp_rate.item(),
        "specificity": specificity.item()
    }

    return metrics

def evaluate(model, dataset, datatype=torch.float, singularity_avoiding=False):
    
    model.eval()

    pred = model(dataset['input'].to(dtype=datatype), singularity_avoiding=singularity_avoiding) 
    pred_labels = torch.argmax(pred, dim=1).squeeze()
    true_labels = dataset['label'].int()
    accuracy = (torch.sum(pred_labels == true_labels) / torch.numel(true_labels)).item()

    cm = compute_confusion_matrix(pred_labels, true_labels).cpu()

    return accuracy, cm


def train_model_val(model, train_loader, val_loader, opt, loss_fn, steps, lamb=0, early_stopping=None):

    accuracy_history = []
    loss_history = []
    val_acc_history = []
    # val_loss_history = []

    if early_stopping is None:
        early_stopping = steps
    no_improvement_count = 0
    best_val = 0
    best_loss = float('inf')

    for i in range(steps):
        train_batch_num = 0
        val_batch_num = 0
        running_train_accuracy = 0
        running_train_loss = 0
        running_val_accuracy = 0
        running_val_loss = 0

        for batch_inputs, batch_labels in train_loader:
            model.train()

            inputs = batch_inputs.float().to(device)
            labels = batch_labels.to(device)
            global loss, outputs
            # Most optimizers just use optimizer.step(), but certains optimizers require optimizer.step(closure) (e.g., LBFGS). It is used when the optimizer evaluates model and gradient multiple times per step.
            def closure():
                global loss, outputs
                opt.zero_grad()
                outputs = model(inputs)
                # print(outputs.float(), labels.long())
                loss = loss_fn(outputs.float(), labels.long())
                reg = model.get_reg(reg_metric='edge_forward_spline_n', lamb_l1=1., lamb_entropy=1., lamb_coef=0., lamb_coefdiff=0.)
                loss = loss + lamb*reg
                loss.backward()
                return loss
            
            opt.step(closure)
            with torch.no_grad():
                preds = torch.argmax(outputs, dim=1)
                batch_accuracy = (torch.sum(preds == labels) / torch.numel(labels)).item()
                running_train_accuracy += batch_accuracy
                batch_loss = loss.item()
                running_train_loss += batch_loss
                train_batch_num += 1

        for batch_inputs, batch_labels in val_loader:
            with torch.no_grad():
                inputs = batch_inputs.float().to(device)
                labels = batch_labels.to(device)
                
                model.eval()
                outputs = model(inputs)

                preds = torch.argmax(outputs, dim=1)

                batch_accuracy = (torch.sum(preds == labels) / torch.numel(labels)).item()
                running_val_accuracy += batch_accuracy

                loss = loss_fn(outputs.float(), labels.long())
                reg = model.get_reg(reg_metric='edge_forward_spline_n', lamb_l1=1., lamb_entropy=1., lamb_coef=0., lamb_coefdiff=0.)
                loss = loss + lamb*reg
                batch_loss = loss.item()
                running_val_loss += batch_loss

                val_batch_num += 1

        train_accuracy = running_train_accuracy / train_batch_num
        train_loss = running_train_loss / train_batch_num
        val_accuracy = running_val_accuracy / val_batch_num
        val_loss = running_val_loss / val_batch_num

        print(f"Epoch: {i}, Train Acc: {train_accuracy}, Loss: {train_loss}, Val Acc: {val_accuracy}, Val Loss: {val_loss}")

        accuracy_history.append(train_accuracy)
        loss_history.append(train_loss)
        val_acc_history.append(val_accuracy)
        # val_loss_history.append(val_loss)

        if val_loss < best_loss:
            best_loss = val_loss
            best_acc = val_accuracy
            no_improvement_count = 0
        else:
            no_improvement_count += 1

        # Early stopping condition
        if no_improvement_count >= early_stopping:
            break
    
    return accuracy_history, loss_history, val_acc_history, best_acc

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


# Hyperparameter Optimization

In [ ]:
## Load dataset and split into folds
dataset = load_dataset([r"../data/merged1_train.csv"], device)

print(f"Dataset of size {dataset['input'].shape}")
print(f"Labels of size {dataset['label'].shape}")

full_dataset = TensorDataset(dataset['input'], dataset['label'])

k_folds = 5
kf = StratifiedKFold(n_splits=k_folds, shuffle=False)

fold_loaders = []

for train_idx, val_idx in kf.split(dataset['input'].cpu(), dataset['label'].cpu()):
    train_subset = Subset(full_dataset, train_idx)
    val_subset = Subset(full_dataset, val_idx)

    train_loader = DataLoader(train_subset, batch_size=len(train_subset), shuffle=True)
    val_loader = DataLoader(val_subset, batch_size=len(val_subset))

    fold_loaders.append((train_loader, val_loader))

fold_loaders_standardized = []

for fold, (train_loader, val_loader) in enumerate(fold_loaders):

    X_train, y_train = next(iter(train_loader)) # This is just a shorthand for "get the first (and only) batch" which contains the entire training fold.
    train_dict = {'input': X_train, 'label': y_train}

    # Standardize training set and compute mean/std
    train_dict, mean, std = standardize_dataset(train_dict)

    class_weights = get_class_weights(train_dict)
    print(class_weights)

    X_val, y_val = next(iter(val_loader))
    val_dict = {'input': X_val, 'label': y_val}

    # Standardize validation set using the corresponding TRAIN mean/std
    val_dict, _, _ = standardize_dataset(val_dict, mean=mean, std=std)

    train_fold = TensorDataset(train_dict['input'], train_dict['label'])
    val_fold = TensorDataset(val_dict['input'], val_dict['label'])

    train_loader_fold = DataLoader(train_fold, batch_size=len(train_fold), shuffle=True)
    val_loader_fold = DataLoader(val_fold, batch_size=len(val_fold), shuffle=False)

    fold_loaders_standardized.append(
        (train_loader_fold, val_loader_fold, class_weights)
    )

Dataset of size torch.Size([92052, 16])
Labels of size torch.Size([92052])
tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6076, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6074, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6074, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)


In [ ]:
# BO KAN

def evaluate_model(log_lr, W, G, log_lamb):
    lr = float(10**log_lr)
    W = int(round(W))
    G = int(round(G))
    lamb = float(10**log_lamb)

    fold_accuracies = []

    for fold, (train_loader, val_loader, class_weights) in enumerate(fold_loaders_standardized):
        print(f"Training fold {fold}")

        model = KAN(width=[16, W, 5], grid=G, k=3, seed=42, device=device).float()

        if torch.cuda.device_count() > 1:
            print("Using", torch.cuda.device_count(), "GPUs!")
            model = nn.DataParallel(model)

        optimizer = LBFGS(model.parameters(), lr)
        criterion = torch.nn.CrossEntropyLoss(weight=class_weights.to(device).float())

        _, _, _, fold_acc = train_model_val(model, train_loader, val_loader, opt=optimizer, loss_fn=criterion, steps=100, lamb=lamb, early_stopping=10)
        # acc = float(max(val_acc_history))
        # fold_accuracies.append(acc)
        fold_accuracies.append(fold_acc)

        del model, optimizer
    # model.plot()

    mean_accuarcy = sum(fold_accuracies) / len(fold_accuracies)

    print("Fold accs:", fold_accuracies)
    print("Mean acc:", mean_accuarcy)

    return mean_accuarcy

# Define search space
pbounds = {
    'log_lr': (-4, -1),     # sweeps log_lr uniformly -> sweeps 10**log_lr on log scale
    'W': (3, 10),
    'G': (3, 10),
    'log_lamb': (-4, -1)      
}

# Run Bayesian Optimization
optimizer = BayesianOptimization(
    f=evaluate_model,
    pbounds=pbounds,
    random_state=42,
    verbose=2
)

# Checkpointing
from bayes_opt.logger import JSONLogger
from bayes_opt.event import Events

logger = JSONLogger(path="./bo_log - KAN.json", reset=False)
optimizer.subscribe(Events.OPTIMIZATION_STEP, logger)

optimizer.maximize(
    init_points=8,
    n_iter=32
)

print("Best result:")
print(optimizer.max)


# BO MiniRocket

In [ ]:
## Load dataset (time series) and split into folds
dataset = load_dataset([r"../data/merged2_train.csv"], device)

print(f"Dataset of size {dataset['input'].shape}")
print(f"Labels of size {dataset['label'].shape}")

full_dataset = TensorDataset(dataset['input'], dataset['label'])

k_folds = 5
kf = StratifiedKFold(n_splits=k_folds, shuffle=False)

fold_loaders = []

for train_idx, val_idx in kf.split(dataset['input'].cpu(), dataset['label'].cpu()):
    train_subset = Subset(full_dataset, train_idx)
    val_subset = Subset(full_dataset, val_idx)

    train_loader = DataLoader(train_subset, batch_size=len(train_subset), shuffle=True)
    val_loader = DataLoader(val_subset, batch_size=len(val_subset))

    fold_loaders.append((train_loader, val_loader))

fold_loaders_standardized = []

for fold, (train_loader, val_loader) in enumerate(fold_loaders):

    X_train, y_train = next(iter(train_loader)) # This is just a shorthand for “get the first (and only) batch” which contains the entire training fold.
    train_dict = {'input': X_train, 'label': y_train}

    # Standardize training set and compute mean/std
    train_dict, mean, std = standardize_dataset_raw(train_dict)

    class_weights = get_class_weights(train_dict)
    print(class_weights)

    X_val, y_val = next(iter(val_loader))
    val_dict = {'input': X_val, 'label': y_val}

    # Standardize validation set using the corresponding TRAINING mean/std
    val_dict, _, _ = standardize_dataset_raw(val_dict, mean=mean, std=std)

    train_fold = TensorDataset(train_dict['input'], train_dict['label'])
    val_fold = TensorDataset(val_dict['input'], val_dict['label'])

    train_loader_fold = DataLoader(train_fold, batch_size=len(train_fold), shuffle=True)
    val_loader_fold = DataLoader(val_fold, batch_size=len(val_fold), shuffle=False)

    fold_loaders_standardized.append(
        (train_loader_fold, val_loader_fold, class_weights)
    )

Dataset of size torch.Size([92052, 80])
Labels of size torch.Size([92052])
tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6076, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6074, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6074, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)


In [56]:
# MiniRocket
from tsai.models.MINIROCKET_Pytorch import MiniRocketFeatures

class MiniRocketNet(nn.Module):
    def __init__(self, input_channels=4, seq_len=20, num_classes=5, num_features=924):
        super().__init__()

        # MiniRocket feature extractor
        self.mr = MiniRocketFeatures(
            c_in=input_channels,    
            seq_len=seq_len,
            num_features=num_features
        )

        # small classifier head
        self.fc = nn.Linear(num_features, num_classes)

    def forward(self, x):
        # x: (batch, channels, seq_len)
        feats = self.mr(x)        # (batch, num_features)
        out = self.fc(feats)      # (batch, num_classes)
        
        return out

In [ ]:
# Train and Optimize

def evaluate_model(log_lr, num_features):

    lr = float(10**log_lr)

    # MiniRocket uses multiples of 84 for number of features. Size of classifier head is equal to num_features.
    # MiniRocket automatically rounds num_features to the nearest multiple of 84, but we'll do it here to ensure that the classifier head is also a multiple of 84.
    num_features = int(round(num_features))
    num_features = int(round(num_features / 84)) * 84
    num_features = max(num_features, 84)

    fold_accuracies = []

    for fold, (train_loader, val_loader, class_weights) in enumerate(fold_loaders_standardized):
        print(f"Training fold {fold}")

        # Assume single-batch
        train_inputs, train_labels = next(iter(train_loader))
        val_inputs, val_labels = next(iter(val_loader))

        # Reshape for MiniRocket
        X_train = train_inputs.view(-1, 20, 4)                  # (batch, sequence, input_channels)
        X_train = X_train.permute(0, 2, 1).float().to(device)     # (batch, channels, sequence)
        y_train = train_labels.long().to(device)

        X_val = val_inputs.view(-1, 20, 4)      # (batch, sequence, input_channels)
        X_val = X_val.permute(0, 2, 1).float().to(device)     # (batch, channels, sequence)
        y_val = val_labels.long().to(device)

        model = MiniRocketNet(input_channels=4, seq_len=20, num_classes=5, num_features=num_features).float().to(device)
        model.mr.fit(X_train)

        if torch.cuda.device_count() > 1:
            print("Using", torch.cuda.device_count(), "GPUs!")
            model = nn.DataParallel(model)

        optimizer = torch.optim.Adam(model.fc.parameters(), lr=lr) # model.mr contains no trainable parameters, so we only optimize the fc layer
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device).float())

        with torch.no_grad():
            train_feats = model.mr(X_train)
            val_feats = model.mr(X_val)

        # best_val = 0.0
        best_loss = float('inf')
        no_improvement_count = 0
        early_stopping = 10

        # val_acc_history = []

        # Train and validate
        for epoch in range(1000):
            model.fc.train()   
            optimizer.zero_grad()

            outputs = model.fc(train_feats)
            loss = criterion(outputs, y_train)

            loss.backward()
            optimizer.step()

            train_accuracy = (outputs.argmax(1) == y_train).float().mean().item()

            # Validate
            with torch.no_grad():
                model.fc.eval()
                outputs = model.fc(val_feats)
                val_accuracy = (outputs.argmax(1) == y_val).float().mean().item()
                # val_acc_history.append(val_accuracy)

                val_loss = criterion(outputs, y_val)

            print(f"Epoch: {epoch}, Train Acc: {train_accuracy}, Loss: {loss.item()}, Val Acc: {val_accuracy},  Val Loss: {val_loss.item()}")

            # Save best validation loss for early stopping
            if val_loss < best_loss:
                best_loss = val_loss
                fold_acc = val_accuracy
                no_improvement_count = 0
            else:
                no_improvement_count += 1

            # Early stopping condition
            if no_improvement_count >= early_stopping:
                break

        fold_accuracies.append(fold_acc)

    mean_accuarcy = sum(fold_accuracies) / len(fold_accuracies)

    print("Fold accs:", fold_accuracies)
    print("Mean acc:", mean_accuarcy)
    total_train_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f'Total number of trainable parameters: {total_train_params}')

    # Clear memory
    del model, optimizer, X_train, y_train, train_feats, X_val, y_val, val_feats

    return mean_accuarcy

# Define search space
pbounds = {
    'log_lr': (-4, -1),     # sweeps log_lr uniformly -> sweeps 10**log_lr on log scale
    'num_features': (252, 1008)
}

# Run Bayesian Optimization
optimizer = BayesianOptimization(
    f=evaluate_model,
    pbounds=pbounds,
    random_state=42,
    verbose=2
)

# Checkpointing
from bayes_opt.logger import JSONLogger
from bayes_opt.event import Events

logger = JSONLogger(path="./bo_log - MiniRocket.json")
optimizer.subscribe(Events.OPTIMIZATION_STEP, logger)

optimizer.maximize(
    init_points=4,
    n_iter=16
)

print("Best result:")
print(optimizer.max)


# BO CNN

In [ ]:
## Load dataset (time series) and split into folds
dataset = load_dataset([r"../data/merged2_train.csv"], device)

print(f"Dataset of size {dataset['input'].shape}")
print(f"Labels of size {dataset['label'].shape}")

full_dataset = TensorDataset(dataset['input'], dataset['label'])

k_folds = 5
kf = StratifiedKFold(n_splits=k_folds, shuffle=False)

fold_loaders = []

for train_idx, val_idx in kf.split(dataset['input'].cpu(), dataset['label'].cpu()):
    train_subset = Subset(full_dataset, train_idx)
    val_subset = Subset(full_dataset, val_idx)

    train_loader = DataLoader(train_subset, batch_size=len(train_subset), shuffle=True)
    val_loader = DataLoader(val_subset, batch_size=len(val_subset))

    fold_loaders.append((train_loader, val_loader))

fold_loaders_standardized = []

for fold, (train_loader, val_loader) in enumerate(fold_loaders):

    X_train, y_train = next(iter(train_loader)) # This is just a shorthand for “get the first (and only) batch” which contains the entire training fold.
    train_dict = {'input': X_train, 'label': y_train}

    # Standardize training set and compute mean/std
    train_dict, mean, std = standardize_dataset_raw(train_dict)

    class_weights = get_class_weights(train_dict)
    print(class_weights)

    X_val, y_val = next(iter(val_loader))
    val_dict = {'input': X_val, 'label': y_val}

    # Standardize validation set using the corresponding TRAINING mean/std
    val_dict, _, _ = standardize_dataset_raw(val_dict, mean=mean, std=std)

    train_fold = TensorDataset(train_dict['input'], train_dict['label'])
    val_fold = TensorDataset(val_dict['input'], val_dict['label'])

    train_loader_fold = DataLoader(train_fold, batch_size=len(train_fold), shuffle=True)
    val_loader_fold = DataLoader(val_fold, batch_size=len(val_fold), shuffle=False)

    fold_loaders_standardized.append(
        (train_loader_fold, val_loader_fold, class_weights)
    )

Dataset of size torch.Size([92052, 80])
Labels of size torch.Size([92052])
tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6076, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6074, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6074, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)


In [94]:
class SimpleCNN(nn.Module):
    def __init__(self, output_dim=5, num_channels=16, kernel_size=3, hidden_dim=32, dropout=0.1):
        super(SimpleCNN, self).__init__()

        # convolution layers
        self.conv1 = nn.Conv1d(4, num_channels, kernel_size=kernel_size, padding=kernel_size//2)
        self.conv2 = nn.Conv1d(num_channels, num_channels, kernel_size=kernel_size, padding=kernel_size//2)

        self.pool = nn.MaxPool1d(2)

        # fully connected
        self.fc1 = nn.Linear(num_channels * 5, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):

        x = F.relu(self.conv1(x))
        x = self.pool(x)

        x = F.relu(self.conv2(x))
        x = self.pool(x)

        x = torch.flatten(x, 1)

        x = self.dropout(F.relu(self.fc1(x)))
        x = self.fc2(x)

        return x
    

In [ ]:
# Train and Optimize

def evaluate_model(log_lr, log_num_channels, kernel_idx, log_hidden_dim, dropout):

    lr = float(10**log_lr)

    log_num_channels = int(round(log_num_channels))
    num_channels = 2 ** log_num_channels

    kernel_size = kernel_size_space[int(round(kernel_idx))]

    log_hidden_dim = int(round(log_hidden_dim))
    hidden_dim = 2 ** log_hidden_dim

    dropout = float(dropout)

    fold_accuracies = []

    for fold, (train_loader, val_loader, class_weights) in enumerate(fold_loaders_standardized):
        print(f"Training fold {fold}")

        # Assume single-batch
        train_inputs, train_labels = next(iter(train_loader))
        val_inputs, val_labels = next(iter(val_loader))

        # Reshape
        X_train = train_inputs.view(-1, 20, 4)                  # (batch, sequence, input_channels)
        X_train = X_train.permute(0, 2, 1).float().to(device)     # (batch, channels, sequence)
        y_train = train_labels.long().to(device)

        X_val = val_inputs.view(-1, 20, 4)      # (batch, sequence, input_channels)
        X_val = X_val.permute(0, 2, 1).float().to(device)     # (batch, channels, sequence)
        y_val = val_labels.long().to(device)

        model = SimpleCNN(output_dim=5, num_channels=num_channels, kernel_size=kernel_size, hidden_dim=hidden_dim, dropout=dropout).float().to(device)

        if torch.cuda.device_count() > 1:
            print("Using", torch.cuda.device_count(), "GPUs!")
            model = nn.DataParallel(model)

        optimizer = torch.optim.Adam(model.parameters(), lr=lr)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device).float())

        # best_val = 0.0
        best_loss = float('inf')
        no_improvement_count = 0
        early_stopping = 10

        # val_acc_history = []

        # Train and validate
        for epoch in range(1000):
            model.train()   
            optimizer.zero_grad()

            outputs = model(X_train)
            loss = criterion(outputs, y_train)

            loss.backward()
            optimizer.step()

            train_accuracy = (outputs.argmax(1) == y_train).float().mean().item()

            # Validate
            with torch.no_grad():
                model.eval()
                outputs = model(X_val)
                val_accuracy = (outputs.argmax(1) == y_val).float().mean().item()
                # val_acc_history.append(val_accuracy)

                val_loss = criterion(outputs, y_val)

            print(f"Epoch: {epoch}, Train Acc: {train_accuracy}, Loss: {loss.item()}, Val Acc: {val_accuracy},  Val Loss: {val_loss.item()}")

            # Save best validation loss for early stopping
            if val_loss < best_loss:
                best_loss = val_loss
                fold_acc = val_accuracy
                no_improvement_count = 0
            else:
                no_improvement_count += 1

            # Early stopping condition
            if no_improvement_count >= early_stopping:
                break

        fold_accuracies.append(fold_acc)

    mean_accuracy = sum(fold_accuracies) / len(fold_accuracies)

    print("Fold accs:", fold_accuracies)
    print("Mean acc:", mean_accuracy)
    total_train_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f'Total number of trainable parameters: {total_train_params}')

    # Clear memory
    del model, optimizer, X_train, y_train, X_val, y_val

    return mean_accuracy

# Define search space
kernel_size_space = [3, 5, 7]
pbounds = {
    'log_lr': (-4, -1),     # sweeps log_lr uniformly -> sweeps 10**log_lr on log scale
    'log_num_channels': (0.5, 5.5), # evenly sample 2^1 to 2^5
    'kernel_idx': (-0.5, 2.5), # evenly sample 3 kernel sizes
    'log_hidden_dim': (2.5, 6.5), # evenly sample 2^3 to 2^6
    'dropout': (0.1, 0.5)
}

# Run Bayesian Optimization
optimizer = BayesianOptimization(
    f=evaluate_model,
    pbounds=pbounds,
    random_state=42,
    verbose=2
)

# Checkpointing
from bayes_opt.logger import JSONLogger
from bayes_opt.event import Events

logger = JSONLogger(path="./bo_log - CNN - 20260705.json")
optimizer.subscribe(Events.OPTIMIZATION_STEP, logger)

optimizer.maximize(
    init_points=10,
    n_iter=40
)

print("Best result:")
print(optimizer.max)


# BO LSTM

In [ ]:
## Load dataset (time series) and split into folds
dataset = load_dataset([r"../data/merged2_train.csv"], device)

print(f"Dataset of size {dataset['input'].shape}")
print(f"Labels of size {dataset['label'].shape}")

full_dataset = TensorDataset(dataset['input'], dataset['label'])

k_folds = 5
kf = StratifiedKFold(n_splits=k_folds, shuffle=False)

fold_loaders = []

for train_idx, val_idx in kf.split(dataset['input'].cpu(), dataset['label'].cpu()):
    train_subset = Subset(full_dataset, train_idx)
    val_subset = Subset(full_dataset, val_idx)

    train_loader = DataLoader(train_subset, batch_size=len(train_subset), shuffle=True)
    val_loader = DataLoader(val_subset, batch_size=len(val_subset))

    fold_loaders.append((train_loader, val_loader))

fold_loaders_standardized = []

for fold, (train_loader, val_loader) in enumerate(fold_loaders):

    X_train, y_train = next(iter(train_loader)) # This is just a shorthand for “get the first (and only) batch” which contains the entire training fold.
    train_dict = {'input': X_train, 'label': y_train}

    # Standardize training set and compute mean/std
    train_dict, mean, std = standardize_dataset_raw(train_dict)

    class_weights = get_class_weights(train_dict)
    print(class_weights)

    X_val, y_val = next(iter(val_loader))
    val_dict = {'input': X_val, 'label': y_val}

    # Standardize validation set using the corresponding TRAINING mean/std
    val_dict, _, _ = standardize_dataset_raw(val_dict, mean=mean, std=std)

    train_fold = TensorDataset(train_dict['input'], train_dict['label'])
    val_fold = TensorDataset(val_dict['input'], val_dict['label'])

    train_loader_fold = DataLoader(train_fold, batch_size=len(train_fold), shuffle=True)
    val_loader_fold = DataLoader(val_fold, batch_size=len(val_fold), shuffle=False)

    fold_loaders_standardized.append(
        (train_loader_fold, val_loader_fold, class_weights)
    )

Dataset of size torch.Size([92052, 80])
Labels of size torch.Size([92052])
tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6076, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6074, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6074, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)


In [4]:
# LSTM
class SimpleLSTM(nn.Module):
    def __init__(self, input_size=4, hidden_size=32, num_layers=1, output_dim=5, dropout=0.1):
        super(SimpleLSTM, self).__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # LSTM layer
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
        )

        # Fully connected output layer
        self.fc = nn.Linear(hidden_size, output_dim)

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # x: (batch, seq_len, features)
        out, (hn, cn) = self.lstm(x)

        # Take last time step
        out = out[:, -1, :]  # (batch, hidden_size)

        out = self.dropout(F.relu(out))
        out = self.fc(out)

        return out

In [ ]:
# Train and Optimize

import gc

def evaluate_model(log_lr, log_hidden_size, num_layers, dropout):

    lr = float(10**log_lr)

    log_hidden_size = int(round(log_hidden_size))
    hidden_size = 2 ** log_hidden_size

    num_layers = int(round(num_layers))

    dropout = float(dropout)

    fold_accuracies = []

    for fold, (train_loader, val_loader, class_weights) in enumerate(fold_loaders_standardized):
        print(f"Training fold {fold}")

        # Assume single-batch
        train_inputs, train_labels = next(iter(train_loader))
        val_inputs, val_labels = next(iter(val_loader))

        # Reshape for MiniRocket
        X_train = train_inputs.view(-1, 20, 4).float().to(device)                   # (batch, sequence, input_channels)
        y_train = train_labels.long().to(device)

        X_val = val_inputs.view(-1, 20, 4).float().to(device)      # (batch, sequence, input_channels)
        y_val = val_labels.long().to(device)

        model = SimpleLSTM(output_dim=5, hidden_size=hidden_size, num_layers=num_layers, dropout=dropout).float().to(device)

        if torch.cuda.device_count() > 1:
            print("Using", torch.cuda.device_count(), "GPUs!")
            model = nn.DataParallel(model)

        optimizer = torch.optim.Adam(model.parameters(), lr=lr)
        criterion = nn.CrossEntropyLoss(weight=class_weights.float().to(device))

        # best_val = 0.0
        best_loss = float('inf')
        no_improvement_count = 0
        early_stopping = 10

        # val_acc_history = []

        # Train and validate
        for epoch in range(1000):
            model.train()   
            optimizer.zero_grad()

            outputs = model(X_train)
            loss = criterion(outputs, y_train)

            loss.backward()
            optimizer.step()

            train_accuracy = (outputs.argmax(1) == y_train).float().mean().item()

            # Validate
            with torch.no_grad():
                model.eval()
                outputs = model(X_val)
                val_accuracy = (outputs.argmax(1) == y_val).float().mean().item()
                # val_acc_history.append(val_accuracy)

                val_loss = criterion(outputs, y_val)

            print(f"Epoch: {epoch}, Train Acc: {train_accuracy}, Loss: {loss.item()}, Val Acc: {val_accuracy},  Val Loss: {val_loss.item()}")

            # Save best validation loss for early stopping
            if val_loss < best_loss:
                best_loss = val_loss
                fold_acc = val_accuracy
                no_improvement_count = 0
            else:
                no_improvement_count += 1

            # Early stopping condition
            if no_improvement_count >= early_stopping:
                break

        fold_accuracies.append(fold_acc)

    mean_accuracy = sum(fold_accuracies) / len(fold_accuracies)

    print("Fold accs:", fold_accuracies)
    print("Mean acc:", mean_accuracy)
    total_train_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f'Total number of trainable parameters: {total_train_params}')

    # Clear memory
    del model, optimizer, X_train, y_train, X_val, y_val
    gc.collect()
    torch.cuda.empty_cache()

    return mean_accuracy

# Define search space
pbounds = {
    'log_lr': (-4, -1),     # sweeps log_lr uniformly -> sweeps 10**log_lr on log scale
    'log_hidden_size': (2.5, 5.5), # evenly sample 2^3 to 2^5
    'num_layers': (1, 2), # evenly sample 1 to 2 layers
    'dropout': (0.1, 0.5)
}

# Run Bayesian Optimization
optimizer = BayesianOptimization(
    f=evaluate_model,
    pbounds=pbounds,
    random_state=42,
    verbose=2
)

# Checkpointing
from bayes_opt.logger import JSONLogger
from bayes_opt.event import Events

logger = JSONLogger(path="./bo_log - LSTM.json")
optimizer.subscribe(Events.OPTIMIZATION_STEP, logger)

optimizer.maximize(
    init_points=8,
    n_iter=32
)

print("Best result:")
print(optimizer.max)


Loaded 2 points
Training fold 0
Epoch: 0, Train Acc: 0.1003788635134697, Loss: 1.6158980131149292, Val Acc: 0.10037477314472198,  Val Loss: 1.6136239767074585
Epoch: 1, Train Acc: 0.1003788635134697, Loss: 1.6156820058822632, Val Acc: 0.10037477314472198,  Val Loss: 1.6134251356124878
Epoch: 2, Train Acc: 0.1003788635134697, Loss: 1.615523338317871, Val Acc: 0.10037477314472198,  Val Loss: 1.6132287979125977
Epoch: 3, Train Acc: 0.1003788635134697, Loss: 1.6151639223098755, Val Acc: 0.10037477314472198,  Val Loss: 1.613035798072815
Epoch: 4, Train Acc: 0.1003788635134697, Loss: 1.6148943901062012, Val Acc: 0.10037477314472198,  Val Loss: 1.6128449440002441
Epoch: 5, Train Acc: 0.1003788635134697, Loss: 1.6147223711013794, Val Acc: 0.10037477314472198,  Val Loss: 1.6126587390899658
Epoch: 6, Train Acc: 0.1003788635134697, Loss: 1.6144691705703735, Val Acc: 0.10037477314472198,  Val Loss: 1.6124765872955322
Epoch: 7, Train Acc: 0.1003788635134697, Loss: 1.6140369176864624, Val Acc: 0.100

# BO MLP

In [ ]:
## Load dataset and split into folds
dataset = load_dataset([r"../data/merged2_train.csv"], device)

print(f"Dataset of size {dataset['input'].shape}")
print(f"Labels of size {dataset['label'].shape}")

full_dataset = TensorDataset(dataset['input'], dataset['label'])

k_folds = 5
kf = StratifiedKFold(n_splits=k_folds, shuffle=False)

fold_loaders = []

for train_idx, val_idx in kf.split(dataset['input'].cpu(), dataset['label'].cpu()):
    train_subset = Subset(full_dataset, train_idx)
    val_subset = Subset(full_dataset, val_idx)

    train_loader = DataLoader(train_subset, batch_size=len(train_subset), shuffle=True)
    val_loader = DataLoader(val_subset, batch_size=len(val_subset))

    fold_loaders.append((train_loader, val_loader))

fold_loaders_standardized = []

for fold, (train_loader, val_loader) in enumerate(fold_loaders):

    X_train, y_train = next(iter(train_loader)) # This is just a shorthand for “get the first (and only) batch” which contains the entire training fold.
    train_dict = {'input': X_train, 'label': y_train}

    # Standardize training set and compute mean/std
    train_dict, mean, std = standardize_dataset_raw(train_dict)

    class_weights = get_class_weights(train_dict)
    print(class_weights)

    X_val, y_val = next(iter(val_loader))
    val_dict = {'input': X_val, 'label': y_val}

    # Standardize validation set using the corresponding TRAIN mean/std
    val_dict, _, _ = standardize_dataset_raw(val_dict, mean=mean, std=std)

    train_fold = TensorDataset(train_dict['input'], train_dict['label'])
    val_fold = TensorDataset(val_dict['input'], val_dict['label'])

    train_loader_fold = DataLoader(train_fold, batch_size=len(train_fold), shuffle=True)
    val_loader_fold = DataLoader(val_fold, batch_size=len(val_fold), shuffle=False)

    fold_loaders_standardized.append(
        (train_loader_fold, val_loader_fold, class_weights)
    )

Dataset of size torch.Size([92052, 80])
Labels of size torch.Size([92052])
tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6076, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6074, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6074, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)


In [93]:
# MLP
class MLP(nn.Module):
    def __init__(self, input_dim=4, hidden_dim=64, output_dim=5, dropout=0.1, device="cuda"):
        super(MLP, self).__init__()

        self.device = device
        
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, output_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, input):
        x = self.dropout(F.relu(self.fc1(input)))
        x = self.dropout(F.relu(self.fc2(x)))
        x = self.fc3(x)
        return x

In [ ]:
# Train and Optimize


def evaluate_model(log_lr, log_hidden_size, dropout):

    lr = float(10**log_lr)

    log_hidden_size = int(round(log_hidden_size))
    hidden_size = 2 ** log_hidden_size

    dropout = float(dropout)

    fold_accuracies = []

    for fold, (train_loader, val_loader, class_weights) in enumerate(fold_loaders_standardized):
        print(f"Training fold {fold}")

        # Assume single-batch
        train_inputs, train_labels = next(iter(train_loader))
        val_inputs, val_labels = next(iter(val_loader))

        # Reshape for MiniRocket
        X_train = train_inputs.float().to(device)
        y_train = train_labels.long().to(device)

        X_val = val_inputs.float().to(device)
        y_val = val_labels.long().to(device)

        model = MLP(input_dim=80, hidden_dim=hidden_size, output_dim=5, dropout=dropout).float().to(device)

        # if torch.cuda.device_count() > 1:
        #     print("Using", torch.cuda.device_count(), "GPUs!")
        #     model = nn.DataParallel(model)

        optimizer = torch.optim.Adam(model.parameters(), lr=lr)
        criterion = nn.CrossEntropyLoss(weight=class_weights.float().to(device))

        # best_val = 0.0
        best_loss = float('inf')
        no_improvement_count = 0
        early_stopping = 10

        # val_acc_history = []

        # Train and validate
        for epoch in range(1000):
            model.train()   
            optimizer.zero_grad()

            outputs = model(X_train)
            loss = criterion(outputs, y_train)

            loss.backward()
            optimizer.step()

            train_accuracy = (outputs.argmax(1) == y_train).float().mean().item()

            # Validate
            with torch.no_grad():
                model.eval()
                outputs = model(X_val)
                val_accuracy = (outputs.argmax(1) == y_val).float().mean().item()
                # val_acc_history.append(val_accuracy)

                val_loss = criterion(outputs, y_val)

            print(f"Epoch: {epoch}, Train Acc: {train_accuracy}, Loss: {loss.item()}, Val Acc: {val_accuracy},  Val Loss: {val_loss.item()}")

            # Save best validation loss for early stopping
            if val_loss < best_loss:
                best_loss = val_loss
                fold_acc = val_accuracy
                no_improvement_count = 0
            else:
                no_improvement_count += 1

            # Early stopping condition
            if no_improvement_count >= early_stopping:
                break

        fold_accuracies.append(fold_acc)

    mean_accuracy = sum(fold_accuracies) / len(fold_accuracies)

    print("Fold accs:", fold_accuracies)
    print("Mean acc:", mean_accuracy)
    total_train_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f'Total number of trainable parameters: {total_train_params}')

    # Clear memory
    del model, optimizer, X_train, y_train, X_val, y_val

    return mean_accuracy

# Define search space
pbounds = {
    'log_lr': (-4, -1),     # sweeps log_lr uniformly -> sweeps 10**log_lr on log scale
    'log_hidden_size': (2.5, 7.5), # sample 2^3 - 2^7
    'dropout': (0.1, 0.5)
}

# Run Bayesian Optimization
optimizer = BayesianOptimization(
    f=evaluate_model,
    pbounds=pbounds,
    random_state=42,
    verbose=2
)

# Checkpointing
from bayes_opt.logger import JSONLogger
from bayes_opt.event import Events

logger = JSONLogger(path="./bo_log - MLP.json")
optimizer.subscribe(Events.OPTIMIZATION_STEP, logger)

optimizer.maximize(
    init_points=6,
    n_iter=24
)

print("Best result:")
print(optimizer.max)


# BO Decision Tree

In [ ]:
## Load dataset and split into folds
dataset = load_dataset([r"../data/merged2_train.csv"], device)

print(f"Dataset of size {dataset['input'].shape}")
print(f"Labels of size {dataset['label'].shape}")

full_dataset = TensorDataset(dataset['input'], dataset['label'])

k_folds = 5
kf = StratifiedKFold(n_splits=k_folds, shuffle=False)

fold_loaders = []

for train_idx, val_idx in kf.split(dataset['input'].cpu(), dataset['label'].cpu()):
    train_subset = Subset(full_dataset, train_idx)
    val_subset = Subset(full_dataset, val_idx)

    train_loader = DataLoader(train_subset, batch_size=len(train_subset), shuffle=True)
    val_loader = DataLoader(val_subset, batch_size=len(val_subset))

    fold_loaders.append((train_loader, val_loader))

fold_loaders_standardized = []

for fold, (train_loader, val_loader) in enumerate(fold_loaders):

    X_train, y_train = next(iter(train_loader)) # This is just a shorthand for “get the first (and only) batch” which contains the entire training fold.
    train_dict = {'input': X_train, 'label': y_train}

    # Standardize training set and compute mean/std
    train_dict, mean, std = standardize_dataset_raw(train_dict)

    class_weights = get_class_weights(train_dict)
    print(class_weights)

    X_val, y_val = next(iter(val_loader))
    val_dict = {'input': X_val, 'label': y_val}

    # Standardize validation set using the corresponding TRAIN mean/std
    val_dict, _, _ = standardize_dataset_raw(val_dict, mean=mean, std=std)

    train_fold = TensorDataset(train_dict['input'], train_dict['label'])
    val_fold = TensorDataset(val_dict['input'], val_dict['label'])

    train_loader_fold = DataLoader(train_fold, batch_size=len(train_fold), shuffle=True)
    val_loader_fold = DataLoader(val_fold, batch_size=len(val_fold), shuffle=False)

    fold_loaders_standardized.append(
        (train_loader_fold, val_loader_fold, class_weights)
    )

Dataset of size torch.Size([92052, 80])
Labels of size torch.Size([92052])
tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6076, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6074, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
tensor([1.6074, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)


In [ ]:
# Train and Optimize

import gc

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

def count_dt_parameters(clf):
    tree = clf.tree_
    is_leaf = tree.children_left == -1  # -1 marks leaves (children_right same)
    n_leaves = is_leaf.sum()
    n_internal = tree.node_count - n_leaves

    # internal nodes: (feature index, threshold) actually used
    internal_params = 2 * n_internal

    # leaf nodes: class distribution actually used at inference
    n_classes = tree.value.shape[-1]
    leaf_params = n_leaves * n_classes

    return internal_params + leaf_params, n_internal, n_leaves

def evaluate_model(max_depth, log_ccp_alpha):

    max_depth = int(round(max_depth))
    ccp_alpha = float(10**log_ccp_alpha)

    fold_accuracies = []

    for fold, (train_loader, val_loader, class_weights) in enumerate(fold_loaders_standardized):
        print(f"Training fold {fold}")

        # Assume single-batch
        train_inputs, train_labels = next(iter(train_loader))
        val_inputs, val_labels = next(iter(val_loader))

        X_train = train_inputs.cpu().numpy()
        y_train = train_labels.cpu().numpy().astype(int)

        X_val = val_inputs.cpu().numpy()
        y_val = val_labels.cpu().numpy().astype(int)

        class_weight_dict = {i: class_weights[i] for i in range(0, len(class_weights))}

        model = DecisionTreeClassifier(class_weight=class_weight_dict, max_depth=max_depth, ccp_alpha=ccp_alpha, random_state=42)

        # Train 
        model.fit(X_train, y_train)

        preds = model.predict(X_train)
        train_accuracy = accuracy_score(y_train, preds)

        # Validate
        preds = model.predict(X_val)
        val_accuracy = accuracy_score(y_val, preds)

        print(f"Train Acc: {train_accuracy}, Val Acc: {val_accuracy}")

        fold_accuracies.append(val_accuracy)

    mean_accuracy = sum(fold_accuracies) / len(fold_accuracies)

    print("Fold accs:", fold_accuracies)
    print("Mean acc:", mean_accuracy)
    total_params, _, _ = count_dt_parameters(model)
    print(f'Total number of trainable parameters: {total_params}')

    # Clear memory
    del model, X_train, y_train, X_val, y_val
    gc.collect()
    torch.cuda.empty_cache()

    return mean_accuracy

# Define search space
pbounds = {
    'max_depth': (3.5, 16.5), # evenly sweeps 4 to 16
    'log_ccp_alpha': (-5, -1) # sweeps log_ccp_alpha uniformly -> sweeps 10**log_ccp_alpha on log scale
}

# Run Bayesian Optimization
optimizer = BayesianOptimization(
    f=evaluate_model,
    pbounds=pbounds,
    random_state=42,
    verbose=2
)

# Checkpointing
from bayes_opt.logger import JSONLogger
from bayes_opt.event import Events

logger = JSONLogger(path="./bo_log - DT.json")
optimizer.subscribe(Events.OPTIMIZATION_STEP, logger)

optimizer.maximize(
    init_points=4,
    n_iter=16
)

print("Best result:")
print(optimizer.max)


Training fold 0
Train Acc: 0.7185671025651471, Val Acc: 0.6841562109608387
Training fold 1
Train Acc: 0.7057209978137179, Val Acc: 0.791700613763511
Training fold 2
Train Acc: 0.7619293338040792, Val Acc: 0.6542639869636068
Training fold 3
Train Acc: 0.7620922842942885, Val Acc: 0.6022813688212928
Training fold 4
Train Acc: 0.7581814725292632, Val Acc: 0.6099402498642043
Fold accs: [0.6841562109608387, 0.791700613763511, 0.6542639869636068, 0.6022813688212928, 0.6099402498642043]
Mean acc: 0.6684684860746907
Total number of trainable parameters: 1069
Training fold 0
Train Acc: 0.5926182425550984, Val Acc: 0.5936125142577807
Training fold 1
Train Acc: 0.5914368354585081, Val Acc: 0.6008907718211939
Training fold 2
Train Acc: 0.5989788435946878, Val Acc: 0.6175991309071157
Training fold 3
Train Acc: 0.6209500013579208, Val Acc: 0.5740901683867463
Training fold 4
Train Acc: 0.651000787594036, Val Acc: 0.5055404671374253
Fold accs: [0.5936125142577807, 0.6008907718211939, 0.617599130907115

# Train Model

In [ ]:
# Load the train dataset
dataset = load_dataset([r"../data/merged1_train.csv"], device)
dataset, train_mean, train_std = standardize_dataset(dataset)
class_weights = get_class_weights(dataset)

print(f"Dataset of size {dataset['input'].shape}")
print(f"Labels of size {dataset['label'].shape}")

print(f"Mean of dataset is {train_mean}")
print(f"Standard deviation of dataset is {train_std}")

print(f"Class weights are {class_weights}")

train_loader = DataLoader(TensorDataset(dataset['input'], dataset['label']), batch_size=dataset['input'].shape[0])

# Load the test dataset
test_dataset = load_dataset([r"../data/merged1_test.csv"], device)
test_dataset, _, _ = standardize_dataset(test_dataset, mean=train_mean, std=train_std)
noise = torch.normal(mean=0, std=0, size=test_dataset['input'].shape).to(device)
test_dataset['input'] = test_dataset['input'] + noise

test_loader = DataLoader(TensorDataset(test_dataset['input'], test_dataset['label']), batch_size=test_dataset['input'].shape[0])

print(f"Dataset of size {test_dataset['input'].shape}")
print(f"Labels of size {test_dataset['label'].shape}")

Dataset of size torch.Size([92052, 16])
Labels of size torch.Size([92052])
Mean of dataset is tensor([ 6.2051e+02,  5.3845e+03,  1.1226e+00,  1.6599e+00,  5.1882e+00,
         2.8907e-05, -4.4868e-01,  2.4746e-01,  6.2051e+02,  5.3735e+03,
         1.1245e+00,  1.6639e+00,  3.2169e+03,  1.4050e+05,  1.1075e+00,
         1.6124e+00], device='cuda:0')
Standard deviation of dataset is tensor([1.8413e+02, 6.6617e+03, 1.1227e+00, 3.1770e+00, 1.3523e-02, 3.3300e-05,
        8.5946e-01, 1.8631e+00, 1.8427e+02, 6.6284e+03, 1.1213e+00, 3.1480e+00,
        9.4549e+02, 1.7147e+05, 1.1102e+00, 3.0975e+00], device='cuda:0')
Class weights are tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
Dataset of size torch.Size([22866, 16])
Labels of size torch.Size([22866])


In [ ]:
# Train network: Initial training, pruning, and symbolic formula extraction, test after each step. For pure testing, replace training lines with loading a pre-trained model.

for seed in [42, 43, 44, 45, 46]:
    set_seed(seed)

    model_folder = f'./model_20260705_{seed}'

    # Create a KAN: width=(num_inputs, num_hidden_neurons, num_outputs), spline order (k), grid intervals (grid).
    model = KAN(width=[16,5,5], grid=5, k=3, seed=seed, device=device, ckpt_path=model_folder).float()

    total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f'Total number of parameters: {total_params}')

    # if torch.cuda.device_count() > 1:
    #     print("Using", torch.cuda.device_count(), "GPUs!")
    #     model = nn.DataParallel(model)

    optimizer = LBFGS(model.parameters(), lr=1e-1)
    criterion = torch.nn.CrossEntropyLoss(weight=class_weights.float())

    ## Train initial model
    print("Training initial model")
    accuracy_history, loss_history = train_model(model, train_loader, opt=optimizer, loss_fn=criterion, steps=200, lamb=5.39e-4, early_stopping=True)
    model.log_history('fit')    # save model
    model.plot()

    # Print loss curve
    plt.figure()
    plt.plot(loss_history)
    plt.legend(['train'])
    plt.ylabel('loss')
    plt.xlabel('step')
    plt.show()

    # Print training curve
    plt.figure()
    plt.plot(accuracy_history)
    plt.legend(['train'])
    plt.ylabel('accuracy')
    plt.xlabel('step')
    plt.show()

    # # Print testing curve
    # plt.figure()
    # plt.plot(test_acc_history)
    # plt.legend(['test'])
    # plt.ylabel('accuracy')
    # plt.xlabel('step')
    # plt.show()

    # Test initial model
    accuracy, cm = evaluate(model, test_dataset)
    plot_confusion_matrix(cm, class_names=['benign', 'DoS', 'crypto', 'backdoor', 'recon'], normalize=False, title="")
    print(f"Test Accuracy: {accuracy}")
    metrics = compute_metrics(cm)
    print("Precision per class:", metrics['precision_per_class'])
    print("Recall per class:", metrics['recall_per_class'])
    print("F1 per class:", metrics['f1_per_class'])

    total_params = sum(p.numel() for p in model.parameters())
    print(f"Total parameters: {total_params}")

    ## Prune model
    print("Pruning model")
    model = model.prune()
    model.plot()

    # Re-train
    optimizer = LBFGS(model.parameters(), lr=1e-1, line_search_fn="strong_wolfe")
    criterion = torch.nn.CrossEntropyLoss(weight=class_weights.float())
    accuracy_history, loss_history = train_model(model, train_loader, opt=optimizer, loss_fn=criterion, steps=200, lamb=5.39e-4, early_stopping=True)
    model.log_history('fit')    # save model
    model.plot()

    # Print loss curve
    plt.figure()
    plt.plot(loss_history)
    plt.legend(['train'])
    plt.ylabel('loss')
    plt.xlabel('step')
    plt.show()

    # Print training curve
    plt.figure()
    plt.plot(accuracy_history)
    plt.legend(['train'])
    plt.ylabel('accuracy')
    plt.xlabel('step')
    plt.show()

    # Test model
    accuracy, cm = evaluate(model, test_dataset)
    plot_confusion_matrix(cm, class_names=['benign', 'DoS', 'crypto', 'backdoor', 'recon'], normalize=False, title="")
    print(f"Test Accuracy: {accuracy}")

    metrics = compute_metrics(cm)
    print("Precision per class:", metrics['precision_per_class'])
    print("Recall per class:", metrics['recall_per_class'])
    print("F1 per class:", metrics['f1_per_class'])

    total_params = sum(p.numel() for p in model.parameters())
    print(f"Total parameters: {total_params}")

    ## Extract symbolic formula
    print("Extracting symbolic formula")
    mode = "auto" # "manual"
    if mode == "manual":
        # manual mode
        model.fix_symbolic(0,0,0,'sin')
        model.fix_symbolic(0,1,0,'x^2')
        model.fix_symbolic(1,0,0,'exp')
    elif mode == "auto":
        # automatic mode
        lib = ['x','x^2','x^3','x^4','exp','log','sqrt','tanh','sin','abs']
        model.auto_symbolic(lib=lib, weight_simple=0.8)

    optimizer = LBFGS(model.parameters(), lr=1e-1, line_search_fn="strong_wolfe")
    criterion = torch.nn.CrossEntropyLoss(weight=class_weights.float())
    accuracy_history, loss_history = train_model(model, train_loader, opt=optimizer, loss_fn=criterion, steps=200, lamb=0, early_stopping=True)
    model.log_history('fit')    # save model
    model.plot()

    # Print loss curve
    plt.figure()
    plt.plot(loss_history)
    plt.legend(['train'])
    plt.ylabel('loss')
    plt.xlabel('step')
    plt.show()

    # Print training curve
    plt.figure()
    plt.plot(accuracy_history)
    plt.legend(['train'])
    plt.ylabel('accuracy')
    plt.xlabel('step')
    plt.show()

    # Test model
    accuracy, cm = evaluate(model, test_dataset)
    plot_confusion_matrix(cm, class_names=['benign', 'DoS', 'crypto', 'backdoor', 'recon'], normalize=False, title="")
    print(f"Test Accuracy: {accuracy}")

    metrics = compute_metrics(cm)
    print("Precision per class:", metrics['precision_per_class'])
    print("Recall per class:", metrics['recall_per_class'])
    print("F1 per class:", metrics['f1_per_class'])

    # Print symbolic formulas
    for formula in model.symbolic_formula()[0]:
        print(ex_round(formula, 4))
        print('')

# Testing

In [ ]:
# Load the training data (features)
dataset = load_dataset([r"../data/merged2_train.csv"], device)
dataset, train_mean, train_std = standardize_dataset_raw(dataset)
class_weights = get_class_weights(dataset)

print(f"Dataset of size {dataset['input'].shape}")
print(f"Labels of size {dataset['label'].shape}")

print(f"Mean of dataset is {train_mean}")
print(f"Standard deviation of dataset is {train_std}")

print(f"Class weights are {class_weights}")

train_loader = DataLoader(TensorDataset(dataset['input'], dataset['label']), batch_size=dataset['input'].shape[0])

# Load the test dataset (features)
test_dataset = load_dataset([r"../data/merged2_test.csv"], device)
test_dataset, _, _ = standardize_dataset_raw(test_dataset, mean=train_mean, std=train_std)
noise = torch.normal(mean=0, std=0, size=test_dataset['input'].shape).to(device)
test_dataset['input'] = test_dataset['input'] + noise

print(f"Dataset of size {test_dataset['input'].shape}")
print(f"Labels of size {test_dataset['label'].shape}")


In [ ]:
# Decision Tree

import pickle, sys
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

def count_dt_parameters(clf):
    tree = clf.tree_
    is_leaf = tree.children_left == -1  # -1 marks leaves (children_right same)
    n_leaves = is_leaf.sum()
    n_internal = tree.node_count - n_leaves

    # internal nodes: (feature index, threshold) actually used
    internal_params = 2 * n_internal

    # leaf nodes: class distribution actually used at inference
    n_classes = tree.value.shape[-1]
    leaf_params = n_leaves * n_classes

    return internal_params + leaf_params, n_internal, n_leaves

X_train = dataset['input'].cpu().numpy()
y_train = dataset['label'].cpu().numpy().astype(int)

X_test = test_dataset['input'].cpu().numpy()
y_test = test_dataset['label'].cpu().numpy().astype(int)

class_weight_dict = {i: class_weights[i] for i in range(0, len(class_weights))}

for seed in [42, 43, 44, 45, 46]:
    set_seed(seed)
    
    model = DecisionTreeClassifier(
            class_weight=class_weight_dict,
            max_depth=12,
            ccp_alpha=7.14e-5,
            random_state=seed
        )

    model.fit(X_train, y_train)

    # Save tree to filename
    filename = f'decision_tree_model_flattened_20260709_{seed}.pickle'
    with open(filename, 'wb') as file:
        pickle.dump(model, file)

    preds = model.predict(X_test)
    acc = accuracy_score(y_test, preds)

    print(f"Test Accuracy: {acc}")
    # print(f"Node count: {model.tree_.node_count}")

    cm = compute_confusion_matrix(preds, y_test).cpu()
    metrics = compute_metrics(cm)
    print("Precision per class:", metrics['precision_per_class'])
    print("Recall per class:", metrics['recall_per_class'])
    print("F1 per class:", metrics['f1_per_class'])

    with open(filename, 'rb') as file:
        model = pickle.load(file)
    tree_size = sys.getsizeof(pickle.dumps(model))
    print(f"Decision Tree Size: {tree_size} bytes")

    num_params, n_internal, n_leaves = count_dt_parameters(model)

    print(f"num_params: {num_params}, n_internal: {n_internal}, n_leaves: {n_leaves}")

In [ ]:
## MLP

class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, dropout, output_dim, device="cuda"):
        super(MLP, self).__init__()

        self.device = device
        
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, output_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, input):
        x = self.dropout(F.relu(self.fc1(input)))
        x = self.dropout(F.relu(self.fc2(x)))
        x = self.fc3(x)
        return x

X_train = dataset['input'].float().to(device)
y_train = dataset['label'].long().to(device)

X_test = test_dataset['input'].float().to(device)
y_test = test_dataset['label'].long().to(device)

for seed in [42, 43, 44, 45, 46]:
    set_seed(seed)   

    filename = f'MLP_flattened_20260709_{seed}.pth'

    model = MLP(input_dim=80, hidden_dim=128, dropout=0.12, output_dim=5, device=device).float().to(device)

    if torch.cuda.device_count() > 1:
        print("Using", torch.cuda.device_count(), "GPUs!")
        model = nn.DataParallel(model)

    optimizer = torch.optim.Adam(model.parameters(), lr=7.56e-3)
    criterion = torch.nn.CrossEntropyLoss(weight=class_weights.float())

    best_accuracy = 0.0
    best_loss = float('inf')
    best_model_state = None

    for epoch in range(1000):
        model.train()
        optimizer.zero_grad()
        preds = model(X_train)
        loss = criterion(preds, y_train)
        loss.backward()
        optimizer.step()
        predicted = torch.argmax(preds, dim=1)
        accuracy = (predicted == y_train).float().mean().item()

        if loss < best_loss:
            best_loss = loss
            best_model_state = copy.deepcopy(model.state_dict())
            best_epoch = epoch

    model.load_state_dict(best_model_state)

    print(best_epoch)

    torch.save(model.state_dict(), filename)

    # model_state_dict = torch.load("MLP.pth", weights_only=True)
    # model.load_state_dict(model_state_dict)
    model.eval()

    with torch.no_grad():
        preds = model(X_test)
        predicted = torch.argmax(preds, dim=1)

    accuracy = (predicted == y_test).float().mean().item()

    print("Test Accuracy:", accuracy)

    cm = compute_confusion_matrix(predicted.long(), y_test.long()).cpu()
    metrics = compute_metrics(cm)
    print("Precision per class:", metrics['precision_per_class'])
    print("Recall per class:", metrics['recall_per_class'])
    print("F1 per class:", metrics['f1_per_class'])

total_params = sum(p.numel() for p in model.parameters())
print(f'Total number of parameters: {total_params}')
total_train_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'Total number of trainable parameters: {total_train_params}')

In [ ]:
# Load the training data (time series)
dataset = load_dataset([r"../data/merged2_train.csv"], device)

dataset, train_mean, train_std = standardize_dataset_raw(dataset)
class_weights = get_class_weights(dataset)

print(f"Dataset of size {dataset['input'].shape}")
print(f"Labels of size {dataset['label'].shape}")

print(f"Mean of dataset is {train_mean}")
print(f"Standard deviation of dataset is {train_std}")

print(f"Class weights are {class_weights}")

train_loader = DataLoader(TensorDataset(dataset['input'], dataset['label']), batch_size=dataset['input'].shape[0])

# Load the test dataset
test_dataset = load_dataset([r"../data/merged2_test.csv"], device)
test_dataset, _, _ = standardize_dataset_raw(test_dataset, mean=train_mean, std=train_std)
noise = torch.normal(mean=0, std=0, size=test_dataset['input'].shape).to(device)
test_dataset['input'] = test_dataset['input'] + noise

print(f"Dataset of size {test_dataset['input'].shape}")
print(f"Labels of size {test_dataset['label'].shape}")

Dataset of size torch.Size([92052, 80])
Labels of size torch.Size([92052])
Mean of dataset is tensor([ 620.5126,    5.1882,  620.5081, 3216.9241], device='cuda:0')
Standard deviation of dataset is tensor([1.9821e+02, 1.4552e-02, 1.9831e+02, 1.0171e+03], device='cuda:0')
Class weights are tensor([1.6075, 0.6606, 1.9925, 1.0912, 0.6917], device='cuda:0',
       dtype=torch.float32)
Dataset of size torch.Size([22866, 80])
Labels of size torch.Size([22866])


In [ ]:
# CNN

class SimpleCNN(nn.Module):
    def __init__(self, output_dim=5, num_channels=16, kernel_size=3, hidden_dim=32, dropout=0.1):
        super(SimpleCNN, self).__init__()

        # convolution layers
        self.conv1 = nn.Conv1d(4, num_channels, kernel_size=kernel_size, padding=kernel_size//2)
        self.conv2 = nn.Conv1d(num_channels, num_channels, kernel_size=kernel_size, padding=kernel_size//2)

        self.pool = nn.MaxPool1d(2)

        # fully connected
        self.fc1 = nn.Linear(num_channels * 5, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):

        x = F.relu(self.conv1(x))
        x = self.pool(x)

        x = F.relu(self.conv2(x))
        x = self.pool(x)

        x = torch.flatten(x, 1)

        x = self.dropout(F.relu(self.fc1(x)))
        x = self.fc2(x)

        return x
    
X_train = dataset['input'].view(-1, 20, 4)      # (batch, time, features)
X_train = X_train.permute(0, 2, 1).float().to(device)     # (batch, channels, sequence)
y_train = dataset['label'].long().to(device)

X_test = test_dataset['input'].view(-1, 20, 4)      # (batch, time, features)
X_test = X_test.permute(0, 2, 1).float().to(device)     # (batch, channels, sequence)
y_test = test_dataset['label'].long().to(device)

for seed in [42, 43, 44, 45, 46]:
    set_seed(seed)
        
    model = SimpleCNN(output_dim=5, num_channels=8, kernel_size=3, hidden_dim=32, dropout=0.5).float().to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=2.26e-3)
    criterion = torch.nn.CrossEntropyLoss(weight=class_weights.to(device).float())

    best_accuracy = 0.0
    best_model_state = None
    best_loss = float('inf')

    for epoch in range(1000):
        model.train()
        optimizer.zero_grad()

        preds = model(X_train)
        loss = criterion(preds, y_train)

        loss.backward()
        optimizer.step()

        predicted = torch.argmax(preds, dim=1)
        accuracy = (predicted == y_train).float().mean().item()

        # print(f"Epoch {epoch}, Accuracy: {accuracy:.4f}, Loss: {loss.item():.4f}")

        if loss < best_loss:
            best_loss = loss
            best_model_state = copy.deepcopy(model.state_dict())
            best_epoch = epoch

        # if accuracy > best_accuracy:
        #     best_accuracy = accuracy
        #     best_model_state = model.state_dict()
        
    print(best_epoch)

    model.load_state_dict(best_model_state)

    filename = f"CNN_20260705_{seed}.pth"
    torch.save(model.state_dict(), filename)

    # model_state_dict = torch.load("CNN.pth", weights_only=True)
    # model.load_state_dict(model_state_dict)
    model.eval()


    with torch.no_grad():
        preds = model(X_test)
        predicted = torch.argmax(preds, dim=1)

    accuracy = (predicted == y_test).float().mean().item()

    print("Test Accuracy:", accuracy)

    cm = compute_confusion_matrix(predicted.long(), y_test.long()).cpu()
    metrics = compute_metrics(cm)
    print("Precision per class:", metrics['precision_per_class'])
    print("Recall per class:", metrics['recall_per_class'])
    print("F1 per class:", metrics['f1_per_class'])

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params}")
total_train_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Trainable parameters: {total_train_params}")

In [ ]:
# LSTM

class SimpleLSTM(nn.Module):
    def __init__(self, input_size=4, hidden_size=32, num_layers=1, output_dim=5, dropout=0.1):
        super(SimpleLSTM, self).__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # LSTM layer
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
        )

        # Fully connected output layer
        self.fc = nn.Linear(hidden_size, output_dim)

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # x: (batch, seq_len, features)
        out, (hn, cn) = self.lstm(x)

        # Take last time step
        out = out[:, -1, :]  # (batch, hidden_size)

        out = self.dropout(F.relu(out))
        out = self.fc(out)

        return out

# (batch, seq_len, features)
X_train = dataset['input'].view(-1, 20, 4).float().to(device)
y_train = dataset['label'].long().to(device)

X_test = test_dataset['input'].view(-1, 20, 4).float().to(device)
y_test = test_dataset['label'].long().to(device)

for seed in [42, 43, 44, 45, 46]:
    set_seed(seed)

    model = SimpleLSTM(input_size=4, hidden_size=16, num_layers=1, output_dim=5, dropout=0.36).float().to(device)

    if torch.cuda.device_count() > 1:
        print("Using", torch.cuda.device_count(), "GPUs!")
        model = nn.DataParallel(model)

    optimizer = torch.optim.Adam(model.parameters(), lr=7.97e-2)
    criterion = nn.CrossEntropyLoss(weight=class_weights.to(device).float())

    # best_accuracy = 0.0
    # best_model_state = None

    best_loss = float('inf')
    best_model_state = None
    best_epoch = None

    for epoch in range(1000):
        model.train()
        optimizer.zero_grad()
        
        preds = model(X_train)
        
        loss = criterion(preds, y_train)
        
        loss.backward()
        optimizer.step()
        
        predicted = torch.argmax(preds, dim=1)
        accuracy = (predicted == y_train).float().mean().item()
        
        # print(f"Epoch {epoch}, Accuracy: {accuracy:.4f}, Loss: {loss.item():.4f}")
        
        if loss < best_loss:
            best_loss = loss
            best_model_state = copy.deepcopy(model.state_dict())
            best_epoch = epoch

    model.load_state_dict(best_model_state)

    print(best_epoch)

    filename = f"LSTM_20260705_{seed}.pth"
    torch.save(model.state_dict(), filename)

    # model_state_dict = torch.load("LSTM.pth", weights_only=True)
    # model.load_state_dict(model_state_dict)

    model.eval()

    with torch.no_grad():
        preds = model(X_test)
        predicted = torch.argmax(preds, dim=1)

    accuracy = (predicted == y_test).float().mean().item()
    print("Test Accuracy:", accuracy)

    cm = compute_confusion_matrix(predicted.long(), y_test.long()).cpu()
    metrics = compute_metrics(cm)
    print("Precision per class:", metrics['precision_per_class'])
    print("Recall per class:", metrics['recall_per_class'])
    print("F1 per class:", metrics['f1_per_class'])

total_params = sum(p.numel() for p in model.parameters())
total_train_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total parameters: {total_params}")
print(f"Trainable parameters: {total_train_params}")

In [ ]:
# MiniRocket

from tsai.models.MINIROCKET_Pytorch import MiniRocketFeatures

class MiniRocketNet(nn.Module):
    def __init__(self, input_channels=4, seq_len=20, num_classes=5, num_features=924, random_state=None):
        super().__init__()

        # MiniRocket feature extractor
        self.mr = MiniRocketFeatures(
            c_in=input_channels,
            seq_len=seq_len,
            num_features=num_features,
            random_state=random_state
        )

        # small classifier head
        self.fc = nn.Linear(num_features, num_classes)

    def forward(self, x):
        # x expected shape: (batch, channels, seq_len)
        feats = self.mr(x)        # (batch, num_features)
        out = self.fc(feats)      # (batch, num_classes)
        return out
    
# (batch, channels, sequence_length)
X_train = dataset['input'].view(-1, 20, 4)      # (batch, time, features)
X_train = X_train.permute(0, 2, 1).float().to(device)     # (batch, channels, sequence)
y_train = dataset['label'].long().to(device)

X_test = test_dataset['input'].view(-1, 20, 4)      # (batch, time, features)
X_test = X_test.permute(0, 2, 1).float().to(device)     # (batch, channels, sequence)
y_test = test_dataset['label'].long().to(device)

for seed in [42, 43, 44, 45, 46]:
    set_seed(seed)
    model = MiniRocketNet(input_channels=4, seq_len=20, num_classes=5, num_features=1008, random_state=seed).float().to(device)
    model.mr.fit(X_train)

    if torch.cuda.device_count() > 1:
        print("Using", torch.cuda.device_count(), "GPUs!")
        model = nn.DataParallel(model)

    optimizer = torch.optim.Adam(model.fc.parameters(), lr=1.35e-3) # model.mr contains no trainable parameters, so we only optimized the fc layer
    criterion = nn.CrossEntropyLoss(weight=class_weights.to(device).float())

    with torch.no_grad():
        train_feats = model.mr(X_train)
        test_feats = model.mr(X_test)

    best_loss = float('inf')
    best_model_state = None
    best_epoch = None

    # Train and validate
    for epoch in range(1000):
        model.fc.train()   
        optimizer.zero_grad()

        outputs = model.fc(train_feats)
        loss = criterion(outputs, y_train)

        loss.backward()
        optimizer.step()

        train_accuracy = (outputs.argmax(1) == y_train).float().mean().item()

        with torch.no_grad():
            outputs = model.fc(test_feats)
            test_loss = criterion(outputs, y_test)
            test_accuracy = (outputs.argmax(1) == y_test).float().mean().item()

        # print(f"Epoch: {epoch}, Train Acc: {train_accuracy}, Loss: {loss.item()}, Test Acc: {test_accuracy},  Test Loss: {test_loss.item()}")

        if loss < best_loss:
            best_loss = loss
            best_model_state = copy.deepcopy(model.state_dict())
            best_epoch = epoch

    print(best_epoch)
    model.load_state_dict(best_model_state)

    filename = f"MiniRocket_20260705_{seed}.pth"
    torch.save(model.state_dict(), filename)

    # model_state_dict = torch.load("MiniRocket.pth", weights_only=True)
    # model.load_state_dict(model_state_dict)

    model.eval()

    with torch.no_grad():
        outputs = model(X_test)
        predicted = outputs.argmax(1)
        test_acc = (predicted == y_test).float().mean().item()

    print("Test Accuracy:", test_acc)

    cm = compute_confusion_matrix(predicted.long(), y_test.long()).cpu()
    metrics = compute_metrics(cm)
    print("Precision per class:", metrics['precision_per_class'])
    print("Recall per class:", metrics['recall_per_class'])
    print("F1 per class:", metrics['f1_per_class'])

total_params = sum(p.numel() for p in model.parameters())
total_train_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total parameters: {total_params}")
print(f"Trainable parameters: {total_train_params}")

del model, optimizer, X_train, y_train, train_feats, X_test, y_test, test_feats

In [ ]:
# Load the train dataset, get statistics
dataset = load_dataset([r"../data/merged1_train.csv"], device)
_, train_mean, train_std = standardize_dataset(dataset)


for model_num in [0.1, 1.3, 1.5]:
    print(f"Model number: {model_num}")

    for noise_std in [0, 0.01, 0.02, 0.03, 0.04, 0.05]:
        # Load the test dataset
        test_dataset = load_dataset([r"../data/merged1_test.csv"], device)
        test_dataset, _, _ = standardize_dataset(test_dataset, mean=train_mean, std=train_std)
        noise = torch.normal(mean=0, std=noise_std, size=test_dataset['input'].shape).to(device)
        test_dataset['input'] = test_dataset['input'] + noise

        test_loader = DataLoader(TensorDataset(test_dataset['input'], test_dataset['label']), batch_size=test_dataset['input'].shape[0])

        print(f"Dataset of size {test_dataset['input'].shape}")
        print(f"Labels of size {test_dataset['label'].shape}")

        F1_list = []
        prec_list = []
        recall_list = []

        for seed in [42, 43, 44, 45, 46]:

            set_seed(seed)

            model = KAN.loadckpt(f'./model_20260705_{seed}/' + f'{model_num}').float().to(device)

            # Test model
            accuracy, cm = evaluate(model, test_dataset)
            # plot_confusion_matrix(cm, class_names=['benign', 'DoS', 'crypto', 'backdoor', 'recon'], normalize=True, title="")
            print(f"Test Accuracy: {accuracy}")

            metrics = compute_metrics(cm)
            # print("Precision per class:", metrics['precision_per_class'])
            # print("Recall per class:", metrics['recall_per_class'])
            # print("F1 per class:", metrics['f1_per_class'])

            # for formula in model.symbolic_formula()[0]:
            #     print(ex_round(formula, 4))
            #     print('')

            F1_list.append(np.mean(metrics['f1_per_class']))
            prec_list.append(np.mean(metrics['precision_per_class']))
            recall_list.append(np.mean(metrics['recall_per_class']))


        print(f"For noise_std={noise_std}, F1 score (mean +- std): {np.mean(F1_list)} $\pm$ {np.std(F1_list, ddof=1)}")
        print(f"For noise_std={noise_std}, Precision (mean +- std): {np.mean(prec_list)} $\pm$ {np.std(prec_list, ddof=1)}")
        print(f"For noise_std={noise_std}, Recall (mean +- std): {np.mean(recall_list)} $\pm$ {np.std(recall_list, ddof=1)}")



Model number: 0.1
Dataset of size torch.Size([22866, 16])
Labels of size torch.Size([22866])
Test Accuracy: 0.7736377153852882
Test Accuracy: 0.7734627831715211
Test Accuracy: 0.7756494358436106
Test Accuracy: 0.7758243680573778
Test Accuracy: 0.7710574652322225
For noise_std=0, F1 score (mean +- std): 0.8356464409828186 $\pm$ 0.0019352484679049163
For noise_std=0, Precision (mean +- std): 0.8293278741836548 $\pm$ 0.0024887609239718674
For noise_std=0, Recall (mean +- std): 0.8429172563552856 $\pm$ 0.001373490850223352
Dataset of size torch.Size([22866, 16])
Labels of size torch.Size([22866])
Test Accuracy: 0.766334295460509
Test Accuracy: 0.767602554010321
Test Accuracy: 0.7690020117204583
Test Accuracy: 0.7696142744686434
Test Accuracy: 0.7666404268346015
For noise_std=0.01, F1 score (mean +- std): 0.8308168697357179 $\pm$ 0.0011738694603696345
For noise_std=0.01, Precision (mean +- std): 0.824199526309967 $\pm$ 0.001831887017153433
For noise_std=0.01, Recall (mean +- std): 0.8384978

# Regularization Plots

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

SHOW_ERROR_BARS = True

font_size = 18
width = 0.28

# Avg coeff count
groups1 = [r'$10^{-5}$', r'$10^{-4}$', r'$10^{-3}$', r'$10^{-2}$']

data1_lc07 = [60.8, 45.8, 20.56, 8.36]
data1_lc075 = [48.24, 36.32, 15.52, 6.68]
data1_lc08 = [31.12, 24.52, 12.28, 5.08]
data1_lc085 = [18.44, 16.0, 9.28, 4.36]

err1_lc07 = [10.924, 4.884, 6.586, 1.682]
err1_lc075 = [10.7260430728, 6.03257822162, 5.02513681406, 1.92665513261]
err1_lc08 = [10.676, 2.928, 5.394, 1.446]
err1_lc085 = [5.15635530196, 3.70135110466, 2.57914714586, 0.82945765413]

x1 = np.arange(len(groups1))

fig1, ax1 = plt.subplots(figsize=(4, 3))

ax1.bar(
    x1 - width, data1_lc075, width,
    label=r'$\lambda_c = 0.75$',
    yerr=err1_lc075 if SHOW_ERROR_BARS else None,
    capsize=4 if SHOW_ERROR_BARS else 0,
    error_kw=dict(elinewidth=1, capthick=1),
)

ax1.bar(
    x1, data1_lc08, width,
    label=r'$\lambda_c = 0.80$',
    yerr=err1_lc08 if SHOW_ERROR_BARS else None,
    capsize=4 if SHOW_ERROR_BARS else 0,
    error_kw=dict(elinewidth=1, capthick=1),
)

ax1.bar(
    x1 + width, data1_lc085, width,
    label=r'$\lambda_c = 0.85$',
    yerr=err1_lc085 if SHOW_ERROR_BARS else None,
    capsize=4 if SHOW_ERROR_BARS else 0,
    error_kw=dict(elinewidth=1, capthick=1),
)

ax1.set_ylabel('Avg. Coeff. Count', fontsize=font_size)
ax1.set_xlabel(r'Sparsification $\lambda$', fontsize=font_size)
ax1.set_xticks(x1)
ax1.set_xticklabels(groups1, fontsize=font_size)
ax1.tick_params(axis='y', labelsize=font_size)
ax1.tick_params(axis='x', which='both', length=0)
ax1.legend(fontsize=14, frameon=False, loc='upper right', bbox_to_anchor=(1.04, 1.05))

fig1.tight_layout(pad=0.1)

# Avg term count
groups2 = [r'$10^{-5}$', r'$10^{-4}$', r'$10^{-3}$', r'$10^{-2}$']

data2_lc07 = [19.76, 17.44, 9.8, 4.16]
data2_lc075 = [20.12, 17.4, 9.36, 3.96]
data2_lc08 = [20.04, 16.28, 9.12, 4.4]
data2_lc085 =[16.24, 14.32, 8.56, 4.28]

err2_lc07 = [6.978, 3.59, 2.86, 1.072]
err2_lc075 = [6.66573326799, 3.44383507154, 2.2777181564, 1.04307238483]
err2_lc08 = [4.116, 1.488, 2.334, 0.848]
err2_lc085 = [2.16979261682, 1.59122594247, 2.056210106, 0.76941536246]

x2 = np.arange(len(groups2))

fig2, ax2 = plt.subplots(figsize=(4, 3))

ax2.bar(
    x2 - width, data2_lc075, width,
    label=r'$\lambda_c = 0.75$',
    yerr=err2_lc075 if SHOW_ERROR_BARS else None,
    capsize=4 if SHOW_ERROR_BARS else 0,
    error_kw=dict(elinewidth=1, capthick=1),
)

ax2.bar(
    x2, data2_lc08, width,
    label=r'$\lambda_c = 0.80$',
    yerr=err2_lc08 if SHOW_ERROR_BARS else None,
    capsize=4 if SHOW_ERROR_BARS else 0,
    error_kw=dict(elinewidth=1, capthick=1),
)

ax2.bar(
    x2 + width, data2_lc085, width,
    label=r'$\lambda_c = 0.85$',
    yerr=err2_lc085 if SHOW_ERROR_BARS else None,
    capsize=4 if SHOW_ERROR_BARS else 0,
    error_kw=dict(elinewidth=1, capthick=1),
)

ax2.set_ylabel('Avg. Term Count', fontsize=font_size)
ax2.set_xlabel(r'Sparsification $\lambda$', fontsize=font_size)
ax2.set_xticks(x2)
ax2.set_xticklabels(groups2, fontsize=font_size)
ax2.tick_params(axis='y', labelsize=font_size)
ax2.tick_params(axis='x', which='both', length=0)   # Get rid of horizontal axis ticks
ax2.legend(fontsize=14, frameon=False, loc='upper right', bbox_to_anchor=(1.04, 1.05))

fig2.tight_layout(pad=0.1)


plt.show()